language: python
python:
  - '2.7'
branches:
  only:
    - develop
    - production
cache:
  pip: true
  directories:
    - node_modules
install:
  - nvm install 11.6.0
  - npm install -g npm@6.9.0
  - npm ci
  - pip install awscli
script:
  - if [ "$TRAVIS_BRANCH" = "develop" ]; then npm run build:pre-dev ; fi
  - if [ "$TRAVIS_BRANCH" = "production" ]; then npm run build:production ; fi
deploy:
  - provider: s3
    skip_cleanup: true
    local_dir: build
    access_key_id: "$AWS_ACCESS_KEY_ID"
    secret_access_key:
      secure: "$AWS_SECRET_ACCESS_KEY"
    bucket: "$AWS_BUCKET_PRE_DEV"
    on:
      branch: master
after_deploy:
  - if [ "$TRAVIS_BRANCH" = "master" ]; then AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID;
    fi
  - if [ "$TRAVIS_BRANCH" = "master" ]; then AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY;
    fi
  - chmod +x ./scripts/aws-credentials.sh
  - source ./scripts/aws-credentials.sh
  - echo "done deploying"
  - aws configure set preview.cloudfront true
  - if [ "$TRAVIS_BRANCH" = "develop" ]; then aws cloudfront create-invalidation --distribution-id
    $AWS_CLOUDFRONT_DISTRIBUTION_ID \--paths /*; fi
